version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: .
    command: "node api/server.js"  # Ajusta según tu estructura
    ports:
      - "3000:3000"