export const infoAcademicos = [
  {
    id: 1,
    contacto: "Numero de Contacto",
    ref: "Número de Referencia",
    correo: "Correo Electrónico",
  },
  {
    id: 2,
    nombres: "Alejandra",
    apellido_paterno: "Camacho",
    apellido_materno: "Ferrel",
    correo: "alejandra.camacho@esam.edu.bo",
  },
  {
    id: 3,
    nombres: "María Celeste",
    apellido_paterno: "Aparicio",
    apellido_materno: "Mogro",
    correo: "maria.aparicio@esam.edu.bo",
  },
  {
    id: 4,
    nombres: "Camila",
    apellido_paterno: "Torrico",
    apellido_materno: "Montaño",
    correo: "camila.torrico@esam.edu.bo",
  },
  {
    id: 5,
    nombres: "Rosemary",
    apellido_paterno: "Lopez",
    apellido_materno: "Zapata",
    correo: "rosemary.lopez@esam.edu.bo",
  },
  {
    id: 6,
    nombres: "María Olurcia",
    apellido_paterno: "Maire",
    apellido_materno: "Alcocer",
    correo: "maria.maire@esam.edu.bo",
  },
  {
    id: 7,
    nombres: "Anahí Daniela",
    apellido_paterno: "Vega",
    apellido_materno: "Rojas",
    correo: "anahi.vega@esam.edu.bo",
  },
];
